name: CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up Ruby # for Jekyll
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install dependencies
      run: bundle install
    - name: Build site
      run: bundle exec jekyll build
    - name: S3 Sync
      run: |
        aws s3 sync ${{ github.workspace }}/_site s3://$AWS_S3_BUCKET --delete
      env:
        AWS_S3_BUCKET: <s3-bucket-name>
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: <region>
        SOURCE_DIR: _site
    - name: Invalidate Cloudfront
      uses: chetan/invalidate-cloudfront-action@v2
      env:
        DISTRIBUTION: <cloudfront-dist-id>
        PATHS: '/*'
        AWS_REGION: <region>
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}