name: PR Build

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Running npm install and installing gulp
      run: |
        cd web
        npm install
    - name: Running build
      run: |
        cd web
        npm run build
  